name: fitbuddy-be
on:
  merge:
    merge: ["master"]

  jobs:
    build-phase:
      runs-on: ubuntu-latest
      permissions:
          contents: read

      steps:
        - uses: actions/checkout@v4
        - name: Java 21
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - name: Gradle
          uses: gradle/actions/setup-gradle@v4
        - name: Build
          run: ./gradlew -x test build


    deploy:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: deploy
          run: echo deploy



